all:
	gcc mystring.c hw0101.c -c
	gcc mystring.o hw0101.o -o hw0101
	gcc hw0102.c -o hw0102
	gcc rational.c hw0104.c -c
	gcc rational.o hw0104.o -o hw0104
	gcc hw0105.c -c
	gcc rational.o hw0105.o -o hw0105
