all:
	gcc mystring.c rational.c hw0101.c hw0103.c hw0104.c hw0105.c hw0106.c -c
	gcc mystring.o hw0101.o -o hw0101
	gcc hw0102.c -o hw0102
	gcc mystring.o hw0103.c -o hw0103
	gcc rational.o hw0104.o -o hw0104
	gcc rational.o hw0105.o -o hw0105
	gcc mystring.o hw0106.c -o hw0106
